name: Quiz App
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - run: npm install
    
      - name: Build React App
        run: CI=false npm run build
    
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
        run: surge ./build zeequiz.surge.sh/ --token ${{ secrets.SURGE_TOKEN }}
